### ISSUE TITLE
Ne Android App version 0.9.01

### ISSUE THREAD

**Issue by feh123** [meshtastic/Meshtastic-Android#117]
Just installed this on MediaPad M3 running android 7.0. My tbeam is running 0.9.1.

Cleared tbeams from Android settings, switched off BT and opened the App - allowed BT but did not receive a paring request in the App. On going to Android Settings the pairing sequence started. On adding the pin only received the message incorrect pin pairing failed. Tried this several times with no success. In the App I see the tbeam but when I press the icon I get a grey coloured dot (not the usual green colour) and the message to pair in Settings. I sent in a bug report.

**Comment by geeksville** [comment]
hmm - report hasn't show up in the google console yet.  can you reboot your tab and then run the app (no need to click anything) - that should prompt the little google bug-report thing to run in the background... (otherwise it might wait a couple of days)

**Comment by feh123** [comment]
Okay, done. Thanks.

**Comment by geeksville** [comment]
Thanks!  It came through: 
[com.geeksville.mesh_issue_4518e386cd19614e403892a89decaac6_error_session_5F20060A03A80001129A8A39667E1C72_DNE_0_v2.log](https://github.com/meshtastic/Meshtastic-Android/files/4997879/com.geeksville.mesh_issue_4518e386cd19614e403892a89decaac6_error_session_5F20060A03A80001129A8A39667E1C72_DNE_0_v2.log)

Looking at it now

**Comment by geeksville** [comment]
wow - yeah - it looks like the phone started bonding ("bond state changed 11") and then bonding immediately failed.

Can you try the following: Go to android settings on your phone, then bluetooth, then "previously connected devices", then for each meshtastic device listed, choose "Forget".

Then turn bluetooth off, wait 30 secs (so that it really shuts down) and then back on.  

Then on the android settings page, choose pair new device, and try to pair one of the 0.9.01 radios?  What does it say then?

(My theory is that somehow the old pairing data for the device is not getting deleted on the phone side)

**Comment by feh123** [comment]
My MediaPad M3 does not retain unpaired devices - so there was nothing to forget. But I did switch BT off and on. I got the pairing request and the fail to pair message. I re-tried this several times and it did finally work. So in my BT menu the device was seen as paired. I sent a bug report at this point. In the App it took maybe 3-4 minutes and then the device appeared too. I sent the device a text but it never appeared on the device. The App still shows all the tbeams from my last attempt to connect even though only one is switched on? I switched on a second tbeam and that paired and even received my text. I hit report bug at this point. The first tbeam then also picked up the text! 
So I am rather baffed but the good news is the two seem to work well especially when both are present. Does that make sense?
