### ISSUE TITLE
Traceroute loading bar

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1467]
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

Loading bar until the 30 seconds have elapsed until the next trace route

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GUVWAF** [comment]
You already opened the same issue (#1422), which was closed as "not planned". 
The reason why it's probably not planned is because the 30-second limit is not there because it means the previous traceroute failed, but it's there to limit traffic. The loading bar shouldn't be an encouragement to try a next one as soon as possible.

**Comment by cracky22** [comment]
Thanks for the answer and explanation of how you imagine it, yes, I created the issue twice because it was closed without comment!
