### ISSUE TITLE
Unable to connect T-beam 1 with App

### ISSUE THREAD

**Issue by Discharge87** [meshtastic/Meshtastic-Android#487]
Hello,

i cant connect to both of my devices with the android app on Galaxy S9 + S20plus. 
Binding phones with devices including the bluetooth code is working fine.
But in the app it doesnt show me the devices.

I have installed device firmware 1.3.41 and Android Appversion 1.2.67 and 1.2.64.

I also have an iphone 13 pro. The app from there is working nice.

Regards

**Comment by andrekir** [comment]
you can't mix 1.3 and 1.2 versions, if you're using 1.3 firmware you need the 1.3 app.

https://meshtastic.org/docs/software/other/1.3-enthusiast#meshtastic-13---android

**Comment by Discharge87** [comment]
> you can't mix 1.3 and 1.2 versions, if you're using 1.3 firmware you need the 1.3 app.
> 
> 
> 
> https://meshtastic.org/docs/software/other/1.3-enthusiast#meshtastic-13---android
> 
> 
> 
> 

Still not working with 1.3.41 on Android phone.

**Comment by sachaw** [comment]
@Discharge87 we need a little more to go off than "it's not working" as mentioned above, please ensure your app and firmware versions match. If you are still having trouble please walk us through exactly what you do and what happens, also what you expect would happen.

**Comment by Discharge87** [comment]
> @Discharge87 we need a little more to go off than "it's not working" as mentioned above, please ensure your app and firmware versions match. If you are still having trouble please walk us through exactly what you do and what happens, also what you expect would happen.

Hey,

i have installed the same 1.3.41 versions on all devices. (tbeams, android and iphone versions)
I said "its not working" because its the same error as before.

When i go in the Android app to the nodes- it doesnt show me them.  But i can couple the devices via bluetooth codes(6 numbers). So the system recorgnizes them but not the app. 
On the iphone the app its working fine since few days with both of my meshtastic devices. 

Regards

**Comment by Discharge87** [comment]
![image](https://user-images.githubusercontent.com/114774781/193455748-62eda399-e530-49cf-836d-27b91ea1c84f.jpeg)

**Comment by garthvh** [comment]
Have you clicked the circular + icon in the bottom right and added your device?

**Comment by Discharge87** [comment]
> Have you clicked the circular + icon in the bottom right and added your device?

Yes. 

And i tried to pair my phone and device before i started the meshtastic app and vice versa- no results. 

I also reinstalled the app and the firmware- also no results. (Same versions everywhere 1.3.41)

With the iphone app its working fine.

**Comment by zeitrechnen** [comment]
Hi,

I think I have the same/a similar problem. On my Android devices with app version 1.2.67 and T-Beams with 1.2.65 I had no problem with pairing the devices. I upgraded the T-Beams yesterday to 1.3.41 and the apps also to 1.3.41 but in some cases I cannot successfully finish the pairing process:

- The phone discovers in the system menu the T-Beam and I can pair them. But when I try to add them inside the app, the modal window opens and searches for devices but then closes after a few seconds without showing any device.
- It also happens when I deleted the T-Beam in the bluetooth system settings before and try to start the pairing inside the app without the devices being paired.
- There a differences between the phones/OS versions: On a Huawei phone with Android 10 it works at least with the APK version from Github. On my Pixel 4a with GrapheneOS and Android 13 I have the issue with the version from the Aurora store, F-Droid and the Github APK. On the same device with Graphene and Android 13 there war no problem at all with the combination of the 1.2.67 app version and the T-Beam with 1.2.65.
- Connection with the iOS App is working fine.

Many thanks,
Christian

**Comment by Discharge87** [comment]
@zeitrechnen 

Hey,

yeah, it looks like we have the same problem.

- Pairing works
- Connecting in app works not(it    doesnt show me the (paired) device there)

**Comment by zeitrechnen** [comment]
@andrekir @sachaw Do you need more information? Any ideas what I can do to solve this issue?

**Comment by andrekir** [comment]
@zeitrechnen please create your own issue or if you have questions post at https://meshtastic.discourse.group or join our Discord https://discord.gg/TYHeJpPc
