### ISSUE TITLE
Feature Request: Add option to Mute Contacts

### ISSUE THREAD

**Issue by hatesyourface** [meshtastic/Meshtastic-Android#511]
I feel like soon I'll want a way to disable notifications for the default channel, but would likely still need them for direct messages. Has anyone already talked about this? Thanks

**Comment by tick-hack** [comment]
Any updates?

**Comment by SenorFusion** [comment]
Any chance this could be revisited?

The issue is called "Mute Contacts", but I am asking about Muting Channels.

As meshes grow and default LongFast gets busier, this would be a nice quality of life improvement to be able to Mute specific channels.

Many people talk on default LongFast all day everyday, and I don't want to completely remove it and lose the publish mesh, but it would be really nice not to get a notification for every single one of their messages.

Thanks!

**Comment by thatSFguy** [comment]
I think I'll submit a feature request under the firmware.  With the rise of T-Deck and other messengers, the channel mute should probably reside in the firmware instead.
