### ISSUE TITLE
[Feature Request] Ability to send images

### ISSUE THREAD

**Issue by zjs81** [meshtastic/Meshtastic-Android#555]
I understand that Lora is inherently low bandwidth and each message has a limit of about 200 bytes. But what if we took an image and split it into pieces equal to 200 bytes then sent the pieces one by one and then reconstructed it on the other side? 
What do you all think?

**Comment by hitachi8** [comment]
i think sending text files like a .txt would be far more useful.
for example in an emergency network. sending list of missing person names, item list and stuff.

they would need to implement integrity checks to insure all the text is received intact.

**Comment by zjs81** [comment]
I understand and agree. I tested the Python API by sending an image, and it took a very long time, even after I attempted to compress it. I believe you don't need to add any extra checks for data integrity, as Meshtastic already has that feature built-in. However, what I would suggest is simply labeling the packets, like 1/10, and if you're missing packet 9, you can ask the sender to resend it.

**Comment by hitachi8** [comment]
i think it should do this automatically, i do not believe bothering the user to manually check is a good thing. the software should try and gather the complete thing from the moment it start the transfer. as conditions/positions might be changing it might not be possible to reach the same station later on.

but yes, being able to send text files would be greatly loved by some people. the problem is that it might only be possible to do between node that are connected to a cellphone. i dont know how much memory there is available on each individual node. will repeaters be able to store and "bounce" this data?

**Comment by EternityForest** [comment]
Packets could be sent one at a time, no need to buffer anything on repeaters.  I'm guessing in practice you'd mostly want to send only 1 packet every few minutes, so you didn't clog up a channel.

This could be used for very small SVG avatars and user profile pages, and one frame a week webcams would still be very interesting.

Files could have headers with a version, hash, and timestamp, so two people sending identical files wouldn't repeat the same data, and you could push new versions of the same file for webcams and living documents.

Other nodes that already have a file could pick up where the previous sender left off, if the hashes match.

And you could just advertise the header until someone actually replied, so files without interested receivers don't waste data.

I think there's a lot of applications even with transfer times measured in days.

**Comment by andrekir** [comment]
any feature with the potential to freeze the entire mesh needs to be carefully considered before going into production. closing for now.

**Comment by korbinianbauer** [comment]
Clearly this is a dangerous feature, especially without very solid throttling/shared airtime management present in the meshtastic firmware.

Since my friends and I are basically alone in our region, I've added the capability to a fork nevertheless.
In essence it's sending heavily compressed jpegs as chunkedPayloads via port_num 256, at intervalls that make sure the sending duty cycle is okay-ish.

Realistically, a minimum of 20-50 chunks (packets) are required to get small photos across, which takes about 15-30mins on Medium_Fast at 1% duty cycle.

I'm not gonna open a PR or even link the branch, but for anyone interested in a proof of concept, feel free to check it out. Branch is nativeSendImages.


<a href="https://github.com/user-attachments/assets/df434ecd-7b53-47a5-b4c4-bc6440e6babf">
  <img src="https://github.com/user-attachments/assets/df434ecd-7b53-47a5-b4c4-bc6440e6babf" width="100" />
</a>

<a href="https://github.com/user-attachments/assets/cbfd8542-e1f8-4fb7-99c2-38b166b38842">
  <img src="https://github.com/user-attachments/assets/cbfd8542-e1f8-4fb7-99c2-38b166b38842" width="100" />
</a>

**Comment by jamesarich** [comment]
> Clearly this is a dangerous feature, especially without very solid throttling/shared airtime management present in the meshtastic firmware.
> 
> Since my friends and I are basically alone in our region, I've added the capability to a fork nevertheless. In essence it's sending heavily compressed jpegs as chunkedPayloads via port_num 256, at intervalls that make sure the sending duty cycle is okay-ish.
> 
> Realistically, a minimum of 20-50 chunks (packets) are required to get small photos across, which takes about 15-30mins on Medium_Fast at 1% duty cycle.
> 
> I'm not gonna open a PR or even link the branch, but for anyone interested in a proof of concept, feel free to check it out. Branch is nativeSendImages.
> 
> <img alt="" width="100" src="https://private-user-images.githubusercontent.com/64415847/567324971-df434ecd-7b53-47a5-b4c4-bc6440e6babf.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQxMzAzMTAsIm5iZiI6MTc3NDEzMDAxMCwicGF0aCI6Ii82NDQxNTg0Ny81NjczMjQ5NzEtZGY0MzRlY2QtN2I1My00N2E1LWI0YzQtYmM2NDQwZTZiYWJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzIxVDIxNTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDBlMmEyYTc4NjQ3NWQ3OTcwMWI5YjQ3NzljNmJjZGU2ODlhOTE2M2MwOGY2N2JmNmU0OThmYzRkN2Q3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZCG6I8mFdrD1O4l3M-Ktyl1yJKyuiv4sd52D9ZH8Ry4"><img alt="" width="100" src="https://private-user-images.githubusercontent.com/64415847/567324969-cbfd8542-e1f8-4fb7-99c2-38b166b38842.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQxMzAzMTAsIm5iZiI6MTc3NDEzMDAxMCwicGF0aCI6Ii82NDQxNTg0Ny81NjczMjQ5NjktY2JmZDg1NDItZTFmOC00ZmI3LTk5YzItMzhiMTY2YjM4ODQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzIxVDIxNTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZjQ4MGMxMTIxYjk4ODQ1N2Q0YjJjNGNiNGUzM2ZiNjU4MjAzZmM1YWU2MDdiMDVkMjlhOWU1MWMwMmU4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OvhIR5XIpIfL9gzoVDG4YDeWNSZR7_0nkA-8Hx4Nh_w">

This is a super impressive proof-of-concept.. unfortunately probably won't make it to the main repo due to already congested large networks 😮‍💨 . Very cool nonetheless.

**Comment by korbinianbauer** [comment]
@jamesarich 

Yeah, probably for the best if it doesn't. Thank you for the kind words :)
