### ISSUE TITLE
[feature request] Add a mock GPS Location Provider to the Android Meshtastic App

### ISSUE THREAD

**Issue by wzx6kwxr7j** [meshtastic/Meshtastic-Android#988]
To be able to use the Meshtastic hardware devices that contain a GPS chip as GPS receiver for the phone, the Android Meshtastic app could provide a connection, feeding the mock GPS location of the Android device in way that all other apps on the Android phone are operating on the location data provided by the Meshtastic hardware.

That way the Meshtastic hardware could be used as an external GPS receiver for the phone and could be placed in an exposed position, making the position of the phone unimportant in regards to the GPS signal reception, as the phone uses the signal from the external hardware.

There is an Android app that connects to GPS devices vial Bluetooth and then does exactly what is described above (https://www.apkmirror.com/apk/gg-moblab/bluetooth-gps/). The entire infrastructure should already be there in the Meshtastic app, all that is missing, is feeding the mock location of Android from within the Meshtastic app.

An alternative would be to make the Meshtastic firmware provide the GPS data in NMEA format via Bluetooth, so that the app, mentioned above (https://www.apkmirror.com/apk/gg-moblab/bluetooth-gps/), can connect to the Meshtastic hardware and receive the GPS location data via Bluetooth.

EDIT: Here is an article, describing the procedure of 'injecting' the position data into the Android system on a rather high level view: https://gpswebshop.com/blogs/tech-support-by-platform-android/how-to-connect-an-external-bluetooth-gps-receiver-with-android-phone-or-tablet2021-edition
In the second diagram on the page, in the column on the far left, the box 'mock apps' would be the part that the Meshtastic app would be doing, as well as the part 'disconnect' in the same line of the diagram.

**Comment by andrekir** [comment]
Mock location provider is part of Android Developer Options, it is only intended for testing purposes.

**Comment by asimons04** [comment]
I realize this was closed almost 2 years ago as not planned, but I came across this in a web search because I was wanting to do the same thing.  So here's hoping I can persuade you to at least reconsider the "not planned" status of the original request.

The GPS modules in my nodes are often way better than the ones in my phones, and the nodes are also usually better positioned to receive GPS signals (e.g. not in my pocket +  clipped to my backpack, belt, etc).  

Having the Meshtastic app act as a mock location provider would also allow for turning off location on the phone itself* (thus saving battery) while providing location info for other apps like Organic Maps which pairs wonderfully with Meshtastic.    It would also be beneficial as I like to pair older smartphones (that would otherwise be sitting in a drawer) with Meshtastic nodes, and the GPS in those is often unreliable (e.g. Moto G4).



As for mock location only being intended for testing purposes, well, to be a little blunt, I don't think the demographic of the average Meshtastic enthusiasts really cares how Google thinks their devices should be used.

*I haven't used mock location for a while, so I'm not sure if it can still work independently of location services being on/off in more recent versions of Android.  Assuming not, then the other benefits still apply.
